-- AlterTable
ALTER TABLE `Order` ADD COLUMN `shippingCost` DECIMAL(10, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `shippingMethod` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `Product` ADD COLUMN `altoIn` DOUBLE NULL DEFAULT 2,
    ADD COLUMN `anchoIn` DOUBLE NULL DEFAULT 6,
    ADD COLUMN `largoIn` DOUBLE NULL DEFAULT 6,
    ADD COLUMN `pesoLb` DOUBLE NULL DEFAULT 0.5;
